import fs from 'fs';
import path from 'path';

/**
 * GeoNames-based postal code lookup.
 * 
 * Uses pre-processed per-country JSON files from data/postal/<CC>.json
 * (Generated by scripts/build-postal-data.js from GeoNames allCountries.txt)
 * 
 * Coverage: 121 countries, 1.8M+ postal codes with coordinates.
 */

interface PostalEntry {
    pc: string;   // postal code
    pn: string;   // place name
    lat: number;
    lng: number;
}

// Cache loaded country data to avoid re-reading files
const cache = new Map<string, PostalEntry[]>();

const DATA_DIR = process.env.GEORANKER_DATA_DIR
    ? path.join(process.env.GEORANKER_DATA_DIR, 'postal')
    : path.join(process.cwd(), 'data', 'postal');

/**
 * Check if postal data is available for a country.
 */
export function hasPostalData(countryCode: string): boolean {
    const filePath = path.join(DATA_DIR, `${countryCode.toUpperCase()}.json`);
    return fs.existsSync(filePath);
}

/**
 * Load postal codes for a country (cached after first load).
 */
function loadCountry(countryCode: string): PostalEntry[] {
    const cc = countryCode.toUpperCase();
    if (cache.has(cc)) return cache.get(cc)!;

    const filePath = path.join(DATA_DIR, `${cc}.json`);
    if (!fs.existsSync(filePath)) {
        console.warn(`[PostalLookup] No postal data for country: ${cc}`);
        return [];
    }

    try {
        const raw = fs.readFileSync(filePath, 'utf8');
        const data: PostalEntry[] = JSON.parse(raw);
        cache.set(cc, data);
        console.log(`[PostalLookup] Loaded ${data.length} postal codes for ${cc}`);
        return data;
    } catch (err) {
        console.error(`[PostalLookup] Failed to load ${cc}:`, err);
        return [];
    }
}

/**
 * Find postal codes by EXACT city name match (strict).
 * 
 * Only matches entries where the place name IS the city name,
 * not where the city name appears as a substring. This prevents
 * "Chicago" from matching "Chicago Park" in California.
 */
export function findPostalCodesByCity(
    countryCode: string,
    cityName: string
): { postalCode: string; placeName: string; lat: number; lng: number }[] {
    const entries = loadCountry(countryCode);
    if (entries.length === 0) return [];

    const cityLower = cityName.toLowerCase().trim();

    // STRICT matching only — exact match on place name
    const matching = entries.filter(e => {
        const pnLower = e.pn.toLowerCase().trim();
        return pnLower === cityLower;
    });

    return groupByPostalCode(matching);
}

/**
 * Find postal codes within a bounding box.
 * This is the MOST ACCURATE method — uses geographic coordinates directly.
 * Should be the primary lookup strategy.
 */
export function findPostalCodesInBbox(
    countryCode: string,
    south: number,
    north: number,
    west: number,
    east: number
): { postalCode: string; placeName: string; lat: number; lng: number }[] {
    const entries = loadCountry(countryCode);
    if (entries.length === 0) return [];

    const matching = entries.filter(e =>
        e.lat >= south && e.lat <= north &&
        e.lng >= west && e.lng <= east
    );

    return groupByPostalCode(matching);
}

/**
 * Find postal codes within a radius of a center point.
 * Uses the Haversine formula for accurate distance calculation.
 */
export function findPostalCodesInRadius(
    countryCode: string,
    centerLat: number,
    centerLng: number,
    radiusKm: number
): { postalCode: string; placeName: string; lat: number; lng: number }[] {
    const entries = loadCountry(countryCode);
    if (entries.length === 0) return [];

    const matching = entries.filter(e => {
        const dist = haversineKm(centerLat, centerLng, e.lat, e.lng);
        return dist <= radiusKm;
    });

    return groupByPostalCode(matching);
}

/**
 * Group entries by postal code and compute centroids.
 */
function groupByPostalCode(entries: PostalEntry[]): { postalCode: string; placeName: string; lat: number; lng: number }[] {
    const groups = new Map<string, { pn: string; lats: number[]; lngs: number[] }>();
    for (const entry of entries) {
        if (!groups.has(entry.pc)) {
            groups.set(entry.pc, { pn: entry.pn, lats: [], lngs: [] });
        }
        const g = groups.get(entry.pc)!;
        g.lats.push(entry.lat);
        g.lngs.push(entry.lng);
    }

    return Array.from(groups.entries()).map(([pc, g]) => ({
        postalCode: pc,
        placeName: g.pn,
        lat: g.lats.reduce((a, b) => a + b, 0) / g.lats.length,
        lng: g.lngs.reduce((a, b) => a + b, 0) / g.lngs.length,
    }));
}

/**
 * Haversine distance in kilometers between two lat/lng points.
 */
function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
    const R = 6371; // Earth radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLng = (lng2 - lng1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) ** 2 +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLng / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Get the list of available countries with postal data.
 */
export function getAvailableCountries(): Record<string, number> {
    const indexPath = path.join(DATA_DIR, '_index.json');
    if (!fs.existsSync(indexPath)) return {};
    try {
        return JSON.parse(fs.readFileSync(indexPath, 'utf8'));
    } catch {
        return {};
    }
}
